version: "3.9"

services:
  e-commerce:
    container_name: e-commerce
    volumes:
      - /Users/davidhorvat/GolandProjects/e-commerce:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "15850:2345"
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
#    volumes:
#      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
    driver: local