version: "3.9"

services:
  e-commerce:
    container_name: e-commerce
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8123:8080"
    volumes:
      - /Users/davidhorvat/GolandProjects/e-commerce:/app

networks:
  e-commerce:
    external: true
