version: "3.9"

services:
  postgres:
    container_name: e-commerce-postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
  redis:
    container_name: e-commerce-redis
    image: redis
    ports:
      - "6379:6379"
  e-commerce:
    container_name: e-commerce
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8123:8080"
    volumes:
      - /Users/davidhorvat/GolandProjects/e-commerce:/app
