version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      #      - ./init-scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local


networks:
  e-commerce-db:
    name: e-commerce
    external: false